version: '3'
services:
  app:
    image: bake-budget:latest
    build:
      context: .
    ports:
      - "443:443"
    container_name: app
    depends_on:
      - postgres
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/AppDB
      - MINIO_URL=http://minio:9000

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: alexander
      POSTGRES_PASSWORD: 185206
      POSTGRES_DB: AppDB
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/postgres
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: alexander
      MINIO_ROOT_PASSWORD: 18520655Minio
    command: server --console-address "minio:9001" /data

volumes:
  postgres_data: {}
  minio_storage: {}
